name: Build Vue
on:  [push]
jobs:
  deploy-vue:
    runs-on: ubuntu-latest
    name: deploy vue to pages
    steps:
    - uses: actions/checkout@v4.1.1
      with:
        username: 'yuru-baku'
        reponame: 'InfintyDeck'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
        gitemail: 'ci@example.com'
        gitname:  'CI'
        gitmsg: 'deploy'
        cname: 'none'
    - name: npm install, build and deploy
      run: |
            cd frontend-vue
            npm install
            npm run build
            cd dist
            ln -s index.html 404.html
            if [ "none" !=  ${{ cname }} ]; then echo '${{ cname }}' > CNAME; fi
            git config --global user.email "${{ gitemail }}"
            git config --global user.name "${{ gitname }}"
            git init 
            git add -A
            git commit -m '${{ gitmsg }}'
            git push -f https://${{ username }}:${{ token }}@github.com/${{ username }}/${{ reponame }}.git master:gh-pages
