name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v4.1.1
    - id: Build-Vue
      uses:  xRealNeon/VuePagesAction@1.0.1
      with:
        username: 'yuru-baku'
        reponame: 'InfintyDeck'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
      run: