name: Build and Deploy Vue App

on:
  push:
    branches: [ main ]  # Optional: Filter branches (e.g., only "main")

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set working directory
        working-directory: frontend-vue

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Install dependencies (on cache miss)
        if: steps.cache-dependencies.outputs.cache-hit == false
        run: npm install 

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Build the Vue app
        run: npm run build

      - name: Deploy to GitHub Pages (using GH Pages action)
        uses: actions/deploy-pages@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          clean: true
          build-dir: ./dist  # Relative Pfad zum Build-Verzeichnis
