name: Build Vue
on:  [push]
jobs:
  deploy-vue:
    runs-on: ubuntu-latest
    name: deploy vue to pages
    steps:
    - uses: actions/checkout@v4.1.1
      with:
        username: 'yuru-baku'
        reponame: 'InfintyDeck'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
        gitemail: 'ci@example.com'
        gitname:  'CI'
        gitmsg: 'deploy'
        cname: 'none'
    - name: npm install, build and deploy
      run: |
            cd frontend-vue
            npm install
            npm run build
            cd dist
            ln -s index.html 404.html
            git config --global user.email "ci@example"
            git config --global user.name "ci"
            git init 
            git add -A
            git commit -m 'deploy'
            git push -f https://yuru-baku:${{ inputs.token }}@github.com/yuru-baku/InfintyDeck.git master:gh-pages
