name: Build Vue
on:  [push]
jobs:
  deploy-vue:
    runs-on: ubuntu-latest
    name: deploy vue to pages
    steps:
    - uses: actions/checkout@v4.1.1
    - name: npm install, build and deploy
      run: |
            cd frontend-vue
            npm install
            npm run build
            cd dist
            ln -s index.html 404.html
            git config --global user.email "ci@example"
            git config --global user.name "ci"
            git init 
            git add -A
            git commit -m 'deploy'
            git push -f https://yuru-baku:${{ secrets.GITHUB_TOKEN }}@github.com/yuru-baku/InfintyDeck.git master:gh-pages
