name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v4.1.1
    - id: Build-Vue
      with:
        username: 'yuru-baku'
        reponame: 'InfintyDeck'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
      run: |
              cd frontend-vue
              npm run build
              cd dist
              ln -s index.html 404.html
              git init
              git add -A
              git commit -m '${{ inputs.gitmsg }}'
              git push -f https://${{ inputs.username }}:${{ inputs.token }}@github.com/${{ inputs.username }}/${{ inputs.reponame }}.git master:gh-pages
        shell: bash